### ISSUE TITLE
Deployment strategy

### ISSUE THREAD

**Issue by rye** [frog-pond/deploy#4]
No, we do not need Helm.

But we should start experimenting with defining our service structure in Kubernetes manifest .yml files.  I'm _pretty sure_ we're moving towards having just a `manifest.yml` (or multiple) in the `frog-pond/deploy` repository and that's basically it, since our end goal is to deploy on k8s and not have to deal with sysadmin as much.

@hawkrives / @drewvolz, thoughts?

**Comment by rye** [comment]
(Basically we translate `docker-compose.yml` into multiple `manifest.yml` files, I guess.)

**Comment by hawkrives** [comment]
Sure

**Comment by rye** [comment]
So I need feedback here beyond "Sure".

Do we want to use Docker Swarm over Kubernetes, or Kubernetes over Docker Swarm?

Docker Swarm is easier to deploy and get started with. Kubernetes is more of a second step once we have larger clusters and enough load to necessitate it, I think.  Docker Swarm is more friendly to us from a bootstrapping standpoint (literally `docker swarm join`, basically) but Kubernetes is more hands-off.

There are obviously quorum-related concerns (can only tolerate `(N-1)/2` manager failures, so would want three nodes) in either situation.

**Comment by hawkrives** [comment]
If you give me choices, I can pick from the list :-)

From what you've said, and what I've read, I'd vote Docker Swarm for the time being.

**Comment by rye** [comment]
Closing as I have a more specific ideas to write other Issues.
